### ISSUE TITLE
Green Software Speaker page is broken

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/discussions#128]
### Discussed in https://github.com/orgs/Green-Software-Foundation/discussions/127

<div type='discussions-op-text'>

<sup>Originally posted by **fullo** March  1, 2024</sup>
The Green Software Speaker's link/widget in the [GSF's projects page](https://greensoftware.foundation/projects)  is broken, the link should bring visitors to the [Champion page](https://champions.greensoftware.foundation/champions/)</div>

**Comment by zanete** [comment]
@russelltrow I've updated the DatoCMS to point to the wiki of Champions instead.
